In [38]:
%load_ext autoreload
%autoreload 2

from astar_eps import astar_eps
import networkx as nx
import heapq
import numpy as np
import pickle


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [39]:
test = np.rint(np.emath.logn(1 + 0.0001, np.array([6392.811, 6186.431, 1321.333,   69.259])))
print(test)

[87634. 87306. 71868. 42381.]


In [123]:
file = open("paris_graph_with_weights.pickle", "rb")
graphParis = pickle.load(file)
print(graphParis[135578024])
algo = astar_eps(graphParis, 4)
%matplotlib inline

{135578017: {'weight': array([19.016, 19.016, 19.016,  0.   ])}, 1762073419: {'weight': array([25.668, 25.668, 25.668,  0.   ])}, 2078486565: {'weight': array([21.307, 21.307, 21.307,  0.   ])}, 2812206923: {'weight': array([10.127, 10.127,  0.   ,  0.   ])}}


In [133]:
#resultastar = algo.a_star(graphParis,135578024, 2160034030,100, 0.1)
#resultastar = algo.a_star(graphParis,135578024, 9429648010,100, 0.1)
resultastar = algo.a_star(graphParis,135578024, 17348293,1000, 0.001)
#resultastar = algo.a_star(graphParis,135578024, 277591245)
print(resultastar)

0 noeuds explorés, 0 noeuds restants dans la file
100 noeuds explorés, 40 noeuds restants dans la file
400 noeuds explorés, 109 noeuds restants dans la file
800 noeuds explorés, 137 noeuds restants dans la file
1400 noeuds explorés, 221 noeuds restants dans la file
2000 noeuds explorés, 251 noeuds restants dans la file
2300 noeuds explorés, 247 noeuds restants dans la file
2500 noeuds explorés, 253 noeuds restants dans la file
2800 noeuds explorés, 278 noeuds restants dans la file
3200 noeuds explorés, 296 noeuds restants dans la file
3300 noeuds explorés, 303 noeuds restants dans la file
3400 noeuds explorés, 305 noeuds restants dans la file
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.4239999999986
2066.42

In [127]:
resultastar[2284399764].weights.tolist()

[array([1401.018, 1401.018, 1401.018,    0.   ]),
 array([1418.554, 1409.904, 1098.753,    0.   ]),
 array([1418.959, 1410.309,  904.687,    0.   ]),
 array([1427.651,  930.783,  163.636,    0.   ]),
 array([1429.655,  868.769,  868.769,    0.   ]),
 array([1445.302,  939.784,   37.8  ,    0.   ]),
 array([1447.271,  877.735,  742.638,   10.112]),
 array([1473.623,  968.105,   21.307,    0.   ]),
 array([1496.536,  991.018,    0.   ,    0.   ])]

In [98]:
print(graphParis.nodes[125730])

{'lon': '48.8635232', 'lat': '2.4107318'}


In [94]:
print(algo.build_paths(resultastar)[2])

{0: (array([0, 0, 0, 0]), -1, 135578024, -1, 0), 1: (array([19.016, 19.016, 19.016,  0.   ]), 135578024, 135578017, 0, 1), 681: (array([39.314, 39.314,  0.   ,  0.   ]), 2812206930, 135578017, 44, 681), 2: (array([25.668, 25.668, 25.668,  0.   ]), 135578024, 1762073419, 0, 2), 290: (array([66.264, 66.264, 21.307,  0.   ]), 2354781627, 1762073419, 7, 290), 689: (array([89.177, 89.177,  0.   ,  0.   ]), 2354781627, 1762073419, 253, 689), 3: (array([21.307, 21.307, 21.307,  0.   ]), 135578024, 2078486565, 0, 3), 46: (array([44.22, 44.22,  0.  ,  0.  ]), 2812206588, 2078486565, 42, 46), 4: (array([10.127, 10.127,  0.   ,  0.   ]), 135578024, 2812206923, 0, 4), 6: (array([158.139, 158.139, 158.139,   0.   ]), 2078486565, 1762073410, 3, 6), 252: (array([181.052, 181.052, 136.832,   0.   ]), 2078486565, 1762073410, 46, 252), 320: (array([193.848, 182.792,  21.307,   0.   ]), 5240597749, 1762073410, 292, 320), 709: (array([216.761, 205.705,   0.   ,   0.   ]), 5240597749, 1762073410, 691, 709)

In [95]:
print(resultastar[25032939])

[(array([6009.165, 5939.361, 1222.711,    0.   ]), 25031493, 25032939, 39823, 41759)]


In [136]:
print(algo.get_all_possible_path(resultastar,graphParis,17348293))

[{'distance': 2068.01726063973, 'waypoints': [('48.8976299', '2.3854683'), ('48.8976299', '2.3854683'), ('48.8981910', '2.3860098'), ('48.8982650', '2.3857381'), ('48.8988746', '2.3832761'), ('48.8989354', '2.3825564'), ('48.8989015', '2.3810565'), ('48.8988769', '2.3798375'), ('48.8988446', '2.3781333'), ('48.8988090', '2.3764127'), ('48.8988060', '2.3762704'), ('48.8988036', '2.3761536'), ('48.8987637', '2.3742284'), ('48.8987612', '2.3741172'), ('48.8987594', '2.3740003'), ('48.8987106', '2.3713465'), ('48.8987244', '2.3711722'), ('48.8987240', '2.3703361'), ('48.8987236', '2.3702433'), ('48.8987233', '2.3701562'), ('48.8986969', '2.3683735'), ('48.8986590', '2.3667070'), ('48.8986568', '2.3665541'), ('48.8986414', '2.3656145'), ('48.8986184', '2.3643165'), ('48.8986147', '2.3641450'), ('48.8985877', '2.3629046'), ('48.8985716', '2.3611003'), ('48.8985444', '2.3595365'), ('48.8985372', '2.3593709'), ('48.8985244', '2.3590203')]}, {'distance': 2069.46991969152, 'waypoints': [('48.897

yes


In [84]:
print(resultastar[9429648010])

[(array([ 92.,  92.,  76., -inf]), 245535448, 9429648010, 60443, 60446)]


In [45]:
def lazy_backtrack(input, end):
    counter = 0
    possible_paths = {}
    for record in input.values():
        for k in record:
            if k[2] == end:
                possible_paths[counter] = []
                possible_paths[counter].append(k)
                counter += 1
    for key in possible_paths.keys():
        startfound = False
        curval = possible_paths[key][-1][3]
        while not startfound:
            for record in input.values():
                if startfound:
                    break
                for k in record:
                    if startfound:
                        break
                    if k[4] == curval:
                        possible_paths[key].append(k)
                        curval = k[3]
                        if curval == 0:
                            startfound = True
                            break

    return possible_paths

In [81]:
print(resultastar[2354781627])

[(array([43.903, 43.903, 21.307,  0.   ]), 2078486565, 2354781627,  3,   7)
 (array([ 44.,  44., -inf, -inf]), 2078486565, 2354781627, 46, 388)
 (array([ 41.,  41.,  34., -inf]), 1762073419, 2354781627,  2, 531)]


In [85]:
for record in resultastar.values():
    for k in record:
        if k[2] == 9429648010:
            print(k)

(array([ 92.,  92.,  76., -inf]), 245535448, 9429648010, 60443, 60446)


In [134]:
reverse_dict = dict()
for key, value in resultastar.items():
    for i in value:
        if i[2] in reverse_dict:
            reverse_dict[i[2]].append(i)
        else:
            reverse_dict[i[2]] = []
            reverse_dict[i[2]].append(i)

In [135]:
print(reverse_dict[17348293])

[(array([2066.424, 2066.424, 1992.531,    0.   ]), 277614019, 17348293, 3365, 3682), (array([2067.799, 1686.924, 1525.647,    0.   ]), 277614019, 17348293, 1074, 3722), (array([2073.053, 1699.835, 1098.753,    0.   ]), 277614019, 17348293, 1371, 3812), (array([2073.423, 1700.205,  904.687,    0.   ]), 277614019, 17348293, 1390, 3817), (array([2074.336, 1701.118,  821.152,    0.   ]), 277614019, 17348293, 1435, 3831), (array([2075.398, 1702.18 ,  814.785,    0.   ]), 277614019, 17348293, 1558, 3850), (array([2079.846, 1209.76 ,   37.8  ,    0.   ]), 277614019, 17348293, 1736, 3951), (array([2079.893, 1180.422,  152.181,    0.   ]), 277614019, 17348293, 1740, 3956), (array([2096.436, 1154.675,  993.398,    0.   ]), 277614019, 17348293, 2573, 4402), (array([2101.69 , 1167.586,  566.504,    0.   ]), 277614019, 17348293, 2733, 4536), (array([2102.06 , 1167.956,  372.438,    0.   ]), 277614019, 17348293, 2743, 4550), (array([2102.973, 1168.869,  288.903,    0.   ]), 277614019, 17348293, 2782