In [15]:
%load_ext autoreload
%autoreload 2

from dijkstra import multi_criteria_dijkstra
import networkx as nx
import heapq
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
G = nx.DiGraph()
# definition des noeuds
G.add_node(1,label='A',heuristique=0.0)
G.add_node(2,label='B',heuristique=0.0)
G.add_node(3,label='C',heuristique=0.0)
G.add_node(4,label='D',heuristique=0.0)
G.add_node(5,label='E',heuristique=0.0)
G.add_node(6,label='F',heuristique=0.0)
# definition des aretes
G.add_edge(1,2,weight=[10.0,4.0,2.0,10.0])
G.add_edge(1,3,weight=[6.0,1.0,18.0,10.0])
G.add_edge(3,2,weight=[6.0,2.0,10.0,10.0])
G.add_edge(2,4,weight=[0.0,10.0,12.0,1.0])
G.add_edge(4,6,weight=[10.0,1.0,1.0,1.0])
G.add_edge(4,3,weight=[4.0,0.0,0.0,3.0])
G.add_edge(3,5,weight=[1.0,4.0,8.0,1.0])
G.add_edge(5,4,weight=[5.0,1.0,3.0,7.0])
G.add_edge(5,6,weight=[6.0,0.0,0.0,6.0])

In [17]:
G.nodes[2]['heuristique']

0.0

In [18]:
algo = multi_criteria_dijkstra(G, 4)

In [19]:
algo.dijkstra(G,1,6)

[[13.0, 5.0, 26.0, 17.0]]
[[13.0, 5.0, 26.0, 17.0]]
[[13.0, 5.0, 26.0, 17.0]]
[[13.0, 5.0, 26.0, 17.0]]
[[13.0, 5.0, 26.0, 17.0]]


{1: rec.array([(list([0, 0, 0, 0]), -1, 1, -1, 0)],
           dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]),
 2: rec.array([(list([10.0, 4.0, 2.0, 10.0]), 1, 2, 0, 1),
            (list([12.0, 3.0, 28.0, 20.0]), 3, 2, 2, 3)],
           dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]),
 3: rec.array([(list([6.0, 1.0, 18.0, 10.0]), 1, 3, 0, 2)],
           dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]),
 5: rec.array([(list([7.0, 5.0, 26.0, 11.0]), 3, 5, 2, 4)],
           dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]),
 4: rec.array([(list([12.0, 6.0, 29.0, 18.0]), 5, 4, 4, 5),
            (list([10.0, 14.0, 14.0, 11.0]), 2, 4, 1, 7)],
           dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]),
 6: rec.array([(list([13.0, 5.0, 26.0, 17.

In [20]:
print(algo.a_star(G,1,6))

print(algo.a_star(G,1,6)[4])

{1: rec.array([(list([0.0, 0.0, 0.0, 0.0]), -1, 1, -1, 0)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 2: rec.array([(array([10.,  4.,  2., 10.]), 1, 2, 0, 1),
           (array([12.,  3., 28., 20.]), 3, 2, 2, 3)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 3: rec.array([(array([ 6.,  1., 18., 10.]), 1, 3, 0, 2)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 5: rec.array([(array([ 7.,  5., 26., 11.]), 3, 5, 2, 4)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 4: rec.array([(array([12.,  6., 29., 18.]), 5, 4, 4, 5),
           (array([10., 14., 14., 11.]), 2, 4, 1, 7)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 6: rec.array([(array([13.,  5., 26., 17.]), 5, 6, 4, 6)

In [21]:
G = nx.DiGraph()
# definition des noeuds
G.add_node(1,label='A',heuristique=0.0)
G.add_node(2,label='B',heuristique=0.0)
G.add_node(3,label='C',heuristique=0.0)
G.add_node(4,label='D',heuristique=0.0)
G.add_node(5,label='E',heuristique=0.0)
G.add_node(6,label='F',heuristique=0.0)
# definition des aretes
G.add_edge(1,2,weight=[10.0,4.0,2.0,10.0])
G.add_edge(1,3,weight=[6.0,1.0,18.0,10.0])
G.add_edge(3,2,weight=[6.0,2.0,10.0,10.0])
G.add_edge(2,4,weight=[0.0,10.0,12.0,1.0])
G.add_edge(4,6,weight=[10.0,1.0,1.0,1.0])
G.add_edge(4,3,weight=[4.0,0.0,0.0,3.0])
G.add_edge(3,5,weight=[1.0,4.0,8.0,1.0])
G.add_edge(5,4,weight=[5.0,1.0,3.0,7.0])
G.add_edge(5,6,weight=[6.0,0.0,0.0,6.0])

In [22]:
print(algo.a_star(G,1,6))

{1: rec.array([(list([0.0, 0.0, 0.0, 0.0]), -1, 1, -1, 0)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 2: rec.array([(array([10.,  4.,  2., 10.]), 1, 2, 0, 1),
           (array([12.,  3., 28., 20.]), 3, 2, 2, 3)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 3: rec.array([(array([ 6.,  1., 18., 10.]), 1, 3, 0, 2)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 5: rec.array([(array([ 7.,  5., 26., 11.]), 3, 5, 2, 4)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 4: rec.array([(array([12.,  6., 29., 18.]), 5, 4, 4, 5),
           (array([10., 14., 14., 11.]), 2, 4, 1, 7)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 6: rec.array([(array([13.,  5., 26., 17.]), 5, 6, 4, 6)

In [23]:
h = [[[0 for i in range(4)],[1,0]]]
heapq.heappush(h, [[-1 for i in range(4)],[1,0]])
print(heapq.heappop(h))
print(heapq.heappop(h))

[[-1, -1, -1, -1], [1, 0]]
[[0, 0, 0, 0], [1, 0]]


In [24]:
h = [[[0 for i in range(4)],[1,1]]]
print(h)

[[[0, 0, 0, 0], [1, 1]]]


In [25]:
test = np.asarray(h, dtype=object)
print(test)
print(test[:,1])
print(test[:,1])

[[list([0, 0, 0, 0]) list([1, 1])]]
[list([1, 1])]
[list([1, 1])]


In [26]:
cost_dtype = np.dtype([('weights', list), ('prevnode', int), ('node', int), ('previd', int), ('id', int)])
test = np.recarray((1,), dtype=cost_dtype)
print(test)
test[0] = ([0 for i in range(4)], -1, 1, -1, 0)
test.resize(test.shape[0] + 1)
test[-1] = ([1 for i in range(4)], 1, 1, 1,1)
print(test)
print(test.weights.tolist())
print(type(test.weights))

[(None, 0, 0, 0, 0)]
[(list([0, 0, 0, 0]), -1, 1, -1, 0) (list([1, 1, 1, 1]),  1, 1,  1, 1)]
[[0, 0, 0, 0], [1, 1, 1, 1]]
<class 'numpy.ndarray'>


In [27]:
for u, v, data in G.edges(1, data = True):
    print(u, v, data)

1 2 {'weight': [10.0, 4.0, 2.0, 10.0]}
1 3 {'weight': [6.0, 1.0, 18.0, 10.0]}


In [28]:
a = np.array([5,5,6,3])
b = np.array([2,3,2,1])

np.all(a >= b)

True

In [29]:
v1 = np.array([[1,1,1],[1,1,2],[1,1,3]])
v2 = np.array([[1,1,1],[1,1,2],[1,1,3]])

np.linalg.norm(v1[:,None,:]-v2[None,:,:], axis=-1)

array([[0., 1., 2.],
       [1., 0., 1.],
       [2., 1., 0.]])

In [30]:
v1 = np.array([[1,2,3]])
v2 = np.array([[3,3,3]])

print((v1+v2)/2)

[[2.  2.5 3. ]]


In [31]:
print(type(v1.flatten()))
test = set()
test.add(tuple(v1.flatten()))
print(test)
print(set(tuple(v1.flatten())))

<class 'numpy.ndarray'>
{(1, 2, 3)}
{1, 2, 3}


In [86]:
import pickle

file = open("paris_graph_with_weights.pickle", "rb")
graphParis = pickle.load(file)

In [87]:
algo = multi_criteria_dijkstra(graphParis, 4)

In [88]:
resultastar = algo.a_star(graphParis,135578024, 2160034030)

[0. 0. 0. 0.]
(array([19.016, 19.016, 19.016,  0.   ]), 135578024, 135578017, 0, 1)
[0. 0. 0. 0.]
(array([25.668, 25.668, 25.668,  0.   ]), 135578024, 1762073419, 0, 2)
[0. 0. 0. 0.]
(array([21.307, 21.307, 21.307,  0.   ]), 135578024, 2078486565, 0, 3)
[0. 0. 0. 0.]
(array([10.127, 10.127,  0.   ,  0.   ]), 135578024, 2812206923, 0, 4)
[21.307 21.307 21.307  0.   ]
(array([42.614, 42.614, 42.614,  0.   ]), 2078486565, 135578024, 3, 5)
[21.307 21.307 21.307  0.   ]
(array([158.139, 158.139, 158.139,   0.   ]), 2078486565, 1762073410, 3, 6)
[21.307 21.307 21.307  0.   ]
(array([43.903, 43.903, 21.307,  0.   ]), 2078486565, 2354781627, 3, 7)
[21.307 21.307 21.307  0.   ]
(array([31.713, 31.713, 21.307,  0.   ]), 2078486565, 2812206588, 3, 8)
[158.139 158.139 158.139   0.   ]
(array([227.753, 158.139, 158.139,   0.   ]), 1762073410, 674728522, 6, 9)
[158.139 158.139 158.139   0.   ]
(array([169.195, 158.139, 158.139,   0.   ]), 1762073410, 5240597749, 6, 10)
[158.139 158.139 158.139   0. 

In [89]:
print(resultastar)
for record in resultastar.values():
    for k in record:
        if k[2] == 2160034030:
            print(k)

{135578024: rec.array([(array([0, 0, 0, 0]), -1, 135578024, -1, 0)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 135578017: rec.array([(array([0., 0., 0., 0.]), 135578024, 135578017, 0, 1)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 1762073419: rec.array([(array([0., 0., 0., 0.]), 135578024, 1762073419, 0, 2)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 2078486565: rec.array([(array([0., 0., 0., 0.]), 135578024, 2078486565, 0, 3)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 2812206923: rec.array([(array([0., 0., 0., 0.]), 135578024, 2812206923, 0, 4)],
          dtype=[('weights', 'O'), ('prevnode', '<i8'), ('node', '<i8'), ('previd', '<i8'), ('id', '<i8')]), 1762073410: rec.array([(array([21.307, 21.307, 21.307,  0.   ]), 207

In [91]:
for record in resultastar.values():
    for k in record:
        if k[4] == 14:
            print(k)

(array([213.47, 213.47, 213.47,   0.  ]), 5240597744, 2160034007, 11, 14)


In [92]:
for record in resultastar.values():
    for k in record:
        if k[4] == 11:
            print(k)

(array([158.139, 158.139, 158.139,   0.   ]), 1762073410, 5240597744, 6, 11)


In [93]:
for record in resultastar.values():
    for k in record:
        if k[4] == 6:
            print(k)

(array([21.307, 21.307, 21.307,  0.   ]), 2078486565, 1762073410, 3, 6)


In [94]:
for record in resultastar.values():
    for k in record:
        if k[4] == 3:
            print(k)

(array([0., 0., 0., 0.]), 135578024, 2078486565, 0, 3)


In [145]:
def lazy_backtrack(input, end):
    counter = 0
    possible_paths = {}
    for record in input.values():
        for k in record:
            if k[2] == end:
                possible_paths[counter] = []
                possible_paths[counter].append(k)
                counter += 1
    for key in possible_paths.keys():
        startfound = False
        curval = possible_paths[key][-1][3]
        while not startfound:
            for record in input.values():
                if startfound:
                    break
                for k in record:
                    if startfound:
                        break
                    if k[4] == curval:
                        possible_paths[key].append(k)
                        curval = k[3]
                        if curval == 0:
                            startfound = True
                            break

    return possible_paths

In [146]:
output = lazy_backtrack(resultastar, 2160034030)
print(output[0])

[(array([334.611, 334.611, 213.47 ,   0.   ]), 2160034007, 2160034030, 14, 18), (array([213.47, 213.47, 213.47,   0.  ]), 5240597744, 2160034007, 11, 14), (array([158.139, 158.139, 158.139,   0.   ]), 1762073410, 5240597744, 6, 11), (array([21.307, 21.307, 21.307,  0.   ]), 2078486565, 1762073410, 3, 6), (array([0., 0., 0., 0.]), 135578024, 2078486565, 0, 3)]
